### ISSUE TITLE
CV file should be deleted when attachment is removed

### ISSUE THREAD

**Issue by mikethicke** [mlaa/bp-attachment-xprofile-field-type#3]
Currently when an attached CV is removed from a user's profile, the linked file is not deleted and remains accessible to those with the URL. The file should be deleted when the CV is removed or replaced.

**Comment by babaklar** [comment]
I had a user contact us about this today--we deleted his HCommons account, but his CV is still available online [at this URL](https://hcommons.org/app/uploads/sites/1000360/bp-attachment-xprofile/JonasLeipziger.pdf). He's requesting for us to delete the file.

**Comment by mikethicke** [comment]
The file is removed. Still need to add functionality to automatically delete file when the attachment is removed.

**Comment by mikethicke** [comment]
File deletion when clicking 'Delete' button is handled by hc_custom::bp-attachment-xprofile.php::hc_custom_delete_file()

Delete old file on uploading new CV file: https://github.com/MESH-Research/bp-attachment-xprofile-field-type/commit/518ffe47c3263b9aaa7a114ab9496d7619569362

Cleanup: https://github.com/MESH-Research/bp-attachment-xprofile-field-type/commit/d78956b9d23e2793063e40bd56d9e43e3f04713a
